env:
  matrix:
    #- SCHEME="ChezScheme_master"
    - SCHEME="ChezScheme_v9.5"
    #- SCHEME="Guile_2.0"
    #- SCHEME="Guile_2.2"
    #- SCHEME="Guile_preinstalled"
    #- SCHEME="Larceny_v1.3"
    #- SCHEME="Racket_6.2"
    #- SCHEME="Racket_HEAD"
    #- SCHEME="Racket_preinstalled"
    #- SCHEME="SagittariusScheme_latest"
    #- SCHEME="VicareScheme_0.4.1-devel.3"
    #- SCHEME="Ypsilon"

matrix:
  allow_failures:
    #- os: osx

sudo: false
dist: trusty

addons:
  apt:
    packages:
      ## The "_preinstalled" Schemes.
      #- racket
      #- guile-2.0
      ## Larceny
      #- libc6:i386
      ## Sagittarius and GNU Guile
      #- libgc-dev
      ## GNU Guile
      #- libunistring-dev

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  - linux
  #- osx

compiler:
  - gcc

before_script:
  # Install scheme-ci following https://github.com/weinholt/scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(INSTALL_TARGET=$HOME/opt scheme-ci-master/install-scheme.sh $SCHEME)"
  # Install Akku.csm following https://github.com/weinholt/uuid
  - gpg --keyserver pool.sks-keyservers.net --recv-keys 08272FBB54EEB5072D5BA930E33E61A2E9B8C3A2
  - curl -A "$TRAVIS_REPO_SLUG" -LO "https://akku.weinholt.se/get-akku.sh{,.sig}"
  - gpg --verify get-akku.sh.sig get-akku.sh && bash get-akku.sh
  - ~/bin/akku install

script:
  - source .akku/bin/activate && ./run-tests.sh
